image: python:3.10-slim
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r lur/requirements.txt

check-pocket-numpad:
  script:
    - python -m lur pocket-numpad.yaml
  tags:
    - docker

check-director-operator:
  script:
    - python -m lur director-operator.yaml
  tags:
    - docker

check-megabuttons-proxy:
  script:
    - python -m lur megabuttons-proxy.yaml
  tags:
    - docker
  
check-operator:
  script:
    - python -m lur operator.yaml
  tags:
    - docker

check-worlde-ec9-dmx:
  script:
    - python -m lur worlde_ec9_dmx.yaml
  tags:
    - docker

check-pos:
  script:
    - python -m lur pos.yaml
  tags:
    - docker
