image: python:3.10-slim
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python3 -m pip lur/requirements.txt

check-pocked-numpad:
  script:
    - python3 -m lur pocket-numpad.yaml
