devices:
  - name: midiman
    is_manipulator: true
    is_executor: true
    url: http://127.0.0.1:8093
    user_config:
      midi_devices:
        - accumulate_controls: []
          active: true
          device_name: Arduino_1_2
          hold_delta: 1000
          namespace: default
          reconnect_interval: 1500
          startup_delay: 1500
        - accumulate_controls: []
          active: true
          device_name: Arduino_1_1
          hold_delta: 1000
          namespace: default
          reconnect_interval: 1500
          startup_delay: 1500
  - name: socketman
    is_manipulator: true
    is_executor: true
    url: http://127.0.0.1:8101
    user_config:
      userws:
        onvif-proxy:
            proxyhost: "172.18.191.18"
            proxyport: "8000"
            dial_timeout: 5000
            healthcheck_interval : 2000
        tracker:
            trackerhost: "172.18.191.14"
            trackerport: "8888"
            dial_timeout: 5000
            healthcheck_interval: 2000
rules:
  - include: midi_megabuttons_proxy_separated.yaml
