devices:
  - name: midiman
    is_manipulator: true
    is_executor: true
    url: http://127.0.0.1:8093
    user_config:
      midi_devices:
        - accumulate_controls: []
          active: true
          device_name: WORLDE easy control
          hold_delta: 1000
          namespace: default
          reconnect_interval: 1500
          startup_delay: 1500
  - name: dmxman
    is_manipulator: true
    is_executor: true
    url: http://127.0.0.1:8095
    user_config:
      dmx_devices:
        - alias: DMX1
          path: "COM1" 
          scenes:
            - scene_alias: "scene 1"
              channel_map:
                - scene_channel_id: 0
                  universe_channel_id: 1
                - scene_channel_id: 1
                  universe_channel_id: 2
                - scene_channel_id: 2
                  universe_channel_id: 3   
                - scene_channel_id: 3
                  universe_channel_id: 4
                - scene_channel_id: 4
                  universe_channel_id: 5
                - scene_channel_id: 5
                  universe_channel_id: 6
                - scene_channel_id: 6
                  universe_channel_id: 7   
                - scene_channel_id: 7
                  universe_channel_id: 8
            - scene_alias: "scene 2"
              channel_map:
                - scene_channel_id: 0
                  universe_channel_id: 9
                - scene_channel_id: 1
                  universe_channel_id: 10
                - scene_channel_id: 2
                  universe_channel_id: 11  
                - scene_channel_id: 3
                  universe_channel_id: 12
                - scene_channel_id: 4
                  universe_channel_id: 13
                - scene_channel_id: 5
                  universe_channel_id: 14
                - scene_channel_id: 6
                  universe_channel_id: 15   
                - scene_channel_id: 7
                  universe_channel_id: 16
      artnet_devices:
        - alias: Artnet1
          ip: "172.18.191.119"
          scenes:
            - scene_alias: "scene 1"
              channel_map:
              - scene_channel_id: 0
                universe_channel_id: 11
              - scene_channel_id: 1
                universe_channel_id: 12
              - scene_channel_id: 2
                universe_channel_id: 13   
              - scene_channel_id: 3
                universe_channel_id: 14
              - scene_channel_id: 4
                universe_channel_id: 15
              - scene_channel_id: 5
                universe_channel_id: 16
              - scene_channel_id: 6
                universe_channel_id: 17   
              - scene_channel_id: 7
                universe_channel_id: 18
              - scene_channel_id: 8
                universe_channel_id: 19         
            - scene_alias: "scene 2"
              channel_map:
                - scene_channel_id: 0
                  universe_channel_id: 20
                - scene_channel_id: 1
                  universe_channel_id: 25 
rules:
  - include: midi_worlde_ec9_dmx.yaml
