{
  "hid": {
    "devices": [
      {
        "hold_delta": 1000,
        "max_restart_retries": 10,
        "product_id": 102,
        "restart_devices_interval_sec": 1
      }
    ]
  }
}

#----------------------------------------------

{
  "pelco": {
    "devices": [
      {
        "baud_rate": 9600,
        "name": "pelco1",
        "system_port": "/dev/ttyCONV485"
      }
    ]
  }
}